version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: postgresDB
    environment:
      POSTGRES_USER: marmontDB
      POSTGRES_PASSWORD: marmontDB
      POSTGRES_DB: marmontDB
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: